<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Contato extends \App\Entities\Contato implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Contato' . "\0" . 'id', '' . "\0" . 'App\\Entities\\Contato' . "\0" . 'nome', '' . "\0" . 'App\\Entities\\Contato' . "\0" . 'email', '' . "\0" . 'App\\Entities\\Contato' . "\0" . 'apelido', '' . "\0" . 'App\\Entities\\Contato' . "\0" . 'site', '' . "\0" . 'App\\Entities\\Contato' . "\0" . 'numero', '' . "\0" . 'App\\Entities\\Contato' . "\0" . 'dataInclusao', '' . "\0" . 'App\\Entities\\Contato' . "\0" . 'dataAlteracao', '' . "\0" . 'App\\Entities\\Contato' . "\0" . 'tipoContato', '' . "\0" . 'App\\Entities\\Contato' . "\0" . 'ativo'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Contato' . "\0" . 'id', '' . "\0" . 'App\\Entities\\Contato' . "\0" . 'nome', '' . "\0" . 'App\\Entities\\Contato' . "\0" . 'email', '' . "\0" . 'App\\Entities\\Contato' . "\0" . 'apelido', '' . "\0" . 'App\\Entities\\Contato' . "\0" . 'site', '' . "\0" . 'App\\Entities\\Contato' . "\0" . 'numero', '' . "\0" . 'App\\Entities\\Contato' . "\0" . 'dataInclusao', '' . "\0" . 'App\\Entities\\Contato' . "\0" . 'dataAlteracao', '' . "\0" . 'App\\Entities\\Contato' . "\0" . 'tipoContato', '' . "\0" . 'App\\Entities\\Contato' . "\0" . 'ativo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Contato $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', []);

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', [$nome]);

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getApelido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApelido', []);

        return parent::getApelido();
    }

    /**
     * {@inheritDoc}
     */
    public function setApelido($apelido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApelido', [$apelido]);

        return parent::setApelido($apelido);
    }

    /**
     * {@inheritDoc}
     */
    public function getSite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSite', []);

        return parent::getSite();
    }

    /**
     * {@inheritDoc}
     */
    public function setSite($site)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSite', [$site]);

        return parent::setSite($site);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataInclusao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataInclusao', []);

        return parent::getDataInclusao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataInclusao($dataInclusao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataInclusao', [$dataInclusao]);

        return parent::setDataInclusao($dataInclusao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataAlteracao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataAlteracao', []);

        return parent::getDataAlteracao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataAlteracao($dataAlteracao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataAlteracao', [$dataAlteracao]);

        return parent::setDataAlteracao($dataAlteracao);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoContato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoContato', []);

        return parent::getTipoContato();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoContato(\App\Entities\TipoContato $tipoContato)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoContato', [$tipoContato]);

        return parent::setTipoContato($tipoContato);
    }

    /**
     * {@inheritDoc}
     */
    public function isAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAtivo', []);

        return parent::isAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtivo($ativo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtivo', [$ativo]);

        return parent::setAtivo($ativo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', []);

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero($numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', [$numero]);

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
